window.PHRASE_GLOSS = {
  l01: { words: { nice: "agradable", meet: "conocer", you: "ti" }, vocab: [{ en: "Nice to meet you", es: "Encantado/a de conocerte" }] },
  l02: { words: { hi: "hola", are: "eres", you: "tú", anna: "Anna" }, vocab: [{ en: "Hi", es: "Hola" }, { en: "Are you…?", es: "¿Eres…?" }] },
  l03: { words: { hi: "hola", anna: "Anna", great: "genial", hows: "cómo", going: "va", you: "ti" }, vocab: [{ en: "It's going great", es: "Todo va genial" }, { en: "How's it going with you?", es: "¿Cómo te va a ti?" }] },
  l04: { words: { pete: "Pete", want: "quiero", work: "ejercicio", out: "ejercicio", where: "dónde", gym: "gimnasio" }, vocab: [{ en: "work out", es: "hacer ejercicio" }, { en: "gym", es: "gimnasio" }] },
  l05: { words: { gym: "gimnasio", across: "enfrente", lounge: "salón", next: "al lado", mailroom: "sala de correo" }, vocab: [{ en: "across from", es: "enfrente de" }, { en: "lounge", es: "salón" }, { en: "next to", es: "al lado de" }, { en: "mailroom", es: "sala de correo" }] },
  l06: { words: { do: "verbo auxiliar", not: "no", have: "tengo", job: "trabajo" }, vocab: [{ en: "job", es: "trabajo" }] },
  l07: { words: { okay: "bueno", ill: "me llevo", have: "llevo", the: "la", beef: "carne", then: "entonces" }, vocab: [{ en: "I'll have", es: "me llevo" }, { en: "beef", es: "carne" }] },
  l08: { words: { thanks: "gracias", coming: "venir", pete: "Pete" }, vocab: [{ en: "Thanks", es: "Gracias" }, { en: "coming in", es: "venir" }] },
  l09: { words: { need: "necesito", find: "saber", skills: "habilidades", job: "trabajo" }, vocab: [{ en: "find out", es: "saber" }, { en: "skills", es: "habilidades" }, { en: "job", es: "trabajo" }] },
  l10: { words: { hi: "hola", anna: "Anna", shopping: "compras", list: "lista" }, vocab: [{ en: "shopping list", es: "lista de compras" }] },
  l11: { words: { anna: "Anna", please: "por favor", buy: "compra", ingredients: "ingredientes", list: "lista" }, vocab: [{ en: "buy", es: "comprar" }, { en: "ingredients", es: "ingredientes" }, { en: "list", es: "lista" }] },
  l12: { words: { hello: "hola", want: "quiero", chicken: "pollo", dish: "plato" }, vocab: [{ en: "chicken dish", es: "plato de pollo" }] },
  l13: { words: { excuse: "disculpe", shrimp: "camarón" }, vocab: [{ en: "Excuse me", es: "Disculpe" }, { en: "shrimp", es: "camarón" }] },
  l14: { words: { we: "nosotros", can: "podemos", buy: "comprar", dessert: "postre", ill: "yo" }, vocab: [{ en: "dessert", es: "postre" }, { en: "I'll buy", es: "yo compro" }] },
  l15: { words: { hey: "oye", tastes: "sabe", good: "bien" }, vocab: [{ en: "tastes good", es: "sabe bien" }] },
  l16: { words: { hello: "hola", welcome: "bienvenidos", news: "noticias" }, vocab: [{ en: "welcome", es: "bienvenidos" }, { en: "The News", es: "Las Noticias" }] },
  l17: { words: { pete: "Pete", new: "nueva", city: "ciudad", big: "grande" }, vocab: [{ en: "new", es: "nueva" }, { en: "city", es: "ciudad" }, { en: "big", es: "grande" }] },
  l18: { words: { "people-watching": "observar a la gente", fun: "divertido", makes: "hace", forget: "olvidar", time: "hora" }, vocab: [{ en: "people-watching", es: "observar a la gente" }, { en: "fun", es: "divertido" }, { en: "forget the time", es: "olvidar la hora" }] },
  l19: { words: { yes: "sí", busy: "ocupado", studio: "estudio", light: "luz", recording: "grabando", evening: "de la noche", show: "programa" }, vocab: [{ en: "busy", es: "ocupado" }, { en: "studio light", es: "luz del estudio" }, { en: "recording", es: "grabando" }, { en: "evening show", es: "programa de la noche" }] },
  l20: { words: { need: "tenemos que", return: "volver", work: "trabajo", weather: "clima", beautiful: "hermoso", "people-watching": "observar a la gente", fun: "divertido" }, vocab: [{ en: "return to work", es: "volver al trabajo" }, { en: "weather", es: "clima" }, { en: "beautiful", es: "hermoso" }, { en: "people-watching", es: "observar a la gente" }] },
  l21: { words: { yeah: "sí", learn: "aprendes", little: "un poco", more: "más", every: "cada", day: "día", new: "nuevo", apartment: "apartamento" }, vocab: [{ en: "every day", es: "cada día" }, { en: "apartment", es: "apartamento" }] },
  l22: { words: { sorry: "lo siento", busy: "ocupada", please: "por favor", meet: "conoce", "co-workers": "compañeros de trabajo", remember: "recuerda", working: "trabajando" }, vocab: [{ en: "sorry", es: "lo siento" }, { en: "co-workers", es: "compañeros de trabajo" }, { en: "remember", es: "recuerda" }, { en: "working", es: "trabajando" }] },
  l23: { words: { street: "calle", corner: "esquina" }, vocab: [{ en: "street", es: "calle" }, { en: "corner", es: "esquina" }] },
  l24: { words: { bank: "banco", behind: "detrás", you: "ti" }, vocab: [{ en: "bank", es: "banco" }, { en: "behind", es: "detrás" }] }
};
