window.PHRASE_GLOSS = {
  l01: { words: { nice: "agradable", meet: "conocer", you: "ti" }, vocab: [{ en: "Nice to meet you", es: "Encantado/a de conocerte" }] },
  l02: { words: { hi: "hola", are: "eres", you: "tú", anna: "Anna" }, vocab: [{ en: "Hi", es: "Hola" }, { en: "Are you…?", es: "¿Eres…?" }] },
  l03: { words: { hi: "hola", anna: "Anna", great: "genial", hows: "cómo", going: "va", you: "ti" }, vocab: [{ en: "It's going great", es: "Todo va genial" }, { en: "How's it going with you?", es: "¿Cómo te va a ti?" }] },
  l04: { words: { pete: "Pete", want: "quiero", work: "ejercicio", out: "ejercicio", where: "dónde", gym: "gimnasio" }, vocab: [{ en: "work out", es: "hacer ejercicio" }, { en: "gym", es: "gimnasio" }] },
  l05: { words: { gym: "gimnasio", across: "enfrente", lounge: "salón", next: "al lado", mailroom: "sala de correo" }, vocab: [{ en: "across from", es: "enfrente de" }, { en: "lounge", es: "salón" }, { en: "next to", es: "al lado de" }, { en: "mailroom", es: "sala de correo" }] },
  l06: { words: { do: "verbo auxiliar", not: "no", have: "tengo", job: "trabajo" }, vocab: [{ en: "job", es: "trabajo" }] },
  l07: { words: { okay: "bueno", ill: "me llevo", have: "llevo", the: "la", beef: "carne", then: "entonces" }, vocab: [{ en: "I'll have", es: "me llevo" }, { en: "beef", es: "carne" }] },
  l08: { words: { thanks: "gracias", coming: "venir", pete: "Pete" }, vocab: [{ en: "Thanks", es: "Gracias" }, { en: "coming in", es: "venir" }] },
  l09: { words: { need: "necesito", find: "saber", skills: "habilidades", job: "trabajo" }, vocab: [{ en: "find out", es: "saber" }, { en: "skills", es: "habilidades" }, { en: "job", es: "trabajo" }] },
  l10: { words: { hi: "hola", anna: "Anna", shopping: "compras", list: "lista" }, vocab: [{ en: "shopping list", es: "lista de compras" }] },
  l11: { words: { anna: "Anna", please: "por favor", buy: "compra", ingredients: "ingredientes", list: "lista" }, vocab: [{ en: "buy", es: "comprar" }, { en: "ingredients", es: "ingredientes" }, { en: "list", es: "lista" }] },
  l12: { words: { hello: "hola", want: "quiero", chicken: "pollo", dish: "plato" }, vocab: [{ en: "chicken dish", es: "plato de pollo" }] },
  l13: { words: { excuse: "disculpe", shrimp: "camarón" }, vocab: [{ en: "Excuse me", es: "Disculpe" }, { en: "shrimp", es: "camarón" }] },
  l14: { words: { we: "nosotros", can: "podemos", buy: "comprar", dessert: "postre", ill: "yo" }, vocab: [{ en: "dessert", es: "postre" }, { en: "I'll buy", es: "yo compro" }] },
  l15: { words: { hey: "oye", tastes: "sabe", good: "bien" }, vocab: [{ en: "tastes good", es: "sabe bien" }] },
  l16: { words: { hello: "hola", welcome: "bienvenidos", news: "noticias" }, vocab: [{ en: "welcome", es: "bienvenidos" }, { en: "The News", es: "Las Noticias" }] },
  l17: { words: { pete: "Pete", new: "nueva", city: "ciudad", big: "grande" }, vocab: [{ en: "new", es: "nueva" }, { en: "city", es: "ciudad" }, { en: "big", es: "grande" }] },
  l18: { words: { "people-watching": "observar a la gente", fun: "divertido", makes: "hace", forget: "olvidar", time: "hora" }, vocab: [{ en: "people-watching", es: "observar a la gente" }, { en: "fun", es: "divertido" }, { en: "forget the time", es: "olvidar la hora" }] },
  l19: { words: { yes: "sí", busy: "ocupado", studio: "estudio", light: "luz", recording: "grabando", evening: "de la noche", show: "programa" }, vocab: [{ en: "busy", es: "ocupado" }, { en: "studio light", es: "luz del estudio" }, { en: "recording", es: "grabando" }, { en: "evening show", es: "programa de la noche" }] },
  l20: { words: { need: "tenemos que", return: "volver", work: "trabajo", weather: "clima", beautiful: "hermoso", "people-watching": "observar a la gente", fun: "divertido" }, vocab: [{ en: "return to work", es: "volver al trabajo" }, { en: "weather", es: "clima" }, { en: "beautiful", es: "hermoso" }, { en: "people-watching", es: "observar a la gente" }] },
  l21: { words: { yeah: "sí", learn: "aprendes", little: "un poco", more: "más", every: "cada", day: "día", new: "nuevo", apartment: "apartamento" }, vocab: [{ en: "every day", es: "cada día" }, { en: "apartment", es: "apartamento" }] },
  l22: { words: { sorry: "lo siento", busy: "ocupada", please: "por favor", meet: "conoce", "co-workers": "compañeros de trabajo", remember: "recuerda", working: "trabajando" }, vocab: [{ en: "sorry", es: "lo siento" }, { en: "co-workers", es: "compañeros de trabajo" }, { en: "remember", es: "recuerda" }, { en: "working", es: "trabajando" }] },
  l23: { words: { street: "calle", corner: "esquina" }, vocab: [{ en: "street", es: "calle" }, { en: "corner", es: "esquina" }] },
  l24: { words: { bank: "banco", behind: "detrás", you: "ti" }, vocab: [{ en: "bank", es: "banco" }, { en: "behind", es: "detrás" }] },
k01: { words: { i: "yo", am: "soy", anna: "Anna" }, vocab: [{ en: "I am", es: "soy" }] },
  k02: { words: { have: "tengo", big: "grande", bag: "bolsa", bananas: "plátanos" }, vocab: [{ en: "bag", es: "bolsa" }, { en: "bananas", es: "plátanos" }] },
  k03: { words: { sometimes: "a veces", feel: "sentimos", sad: "tristes" }, vocab: [{ en: "sometimes", es: "a veces" }, { en: "sad", es: "triste" }] },
  k04: { words: { means: "significa", youre: "tienes", years: "años", old: "años" }, vocab: [{ en: "years old", es: "años" }] },
  k05: { words: { what: "qué", can: "puedes", you: "tú", do: "hacer" }, vocab: [{ en: "What can you do?", es: "¿Qué puedes hacer?" }] },
  k06: { words: { city: "ciudad", lots: "mucha", people: "gente", cars: "autos" }, vocab: [{ en: "city", es: "ciudad" }, { en: "cars", es: "autos" }] },
  k07: { words: { show: "mostrar", finland: "Finlandia" }, vocab: [{ en: "show", es: "mostrar" }, { en: "Finland", es: "Finlandia" }] },
  k08: { words: { superhero: "superhéroe", day: "día" }, vocab: [{ en: "superhero", es: "superhéroe" }, { en: "day", es: "día" }] },
  k09: { words: { building: "construyendo", tower: "torre" }, vocab: [{ en: "building", es: "construyendo" }, { en: "tower", es: "torre" }] },
  k10: { words: { movie: "película", starts: "empieza", two: "dos", minutes: "minutos" }, vocab: [{ en: "movie", es: "película" }, { en: "minutes", es: "minutos" }] },
  k11: { words: { beach: "playa", sunny: "soleada", need: "necesito", sunglasses: "lentes de sol" }, vocab: [{ en: "beach", es: "playa" }, { en: "sunglasses", es: "lentes de sol" }] },
  k12: { words: { seeds: "semillas", grow: "crecer", plant: "planta" }, vocab: [{ en: "seeds", es: "semillas" }, { en: "plant", es: "planta" }] },
  k13: { words: { bought: "compré", peppers: "pimientos", farmers: "agricultores", market: "mercado" }, vocab: [{ en: "peppers", es: "pimientos" }, { en: "farmer's market", es: "mercado de agricultores" }] },
  k14: { words: { favorite: "favorito", bug: "bicho", butterfly: "mariposa" }, vocab: [{ en: "bug", es: "bicho" }, { en: "butterfly", es: "mariposa" }] },
  k15: { words: { sit: "sentarte", roast: "asar", marshmallows: "malvaviscos" }, vocab: [{ en: "roast", es: "asar" }, { en: "marshmallows", es: "malvaviscos" }] },
  k16: { words: { some: "algunas", tricks: "trucos" }, vocab: [{ en: "tricks", es: "trucos" }] },
  k17: { words: { family: "familia", three: "tres", people: "personas" }, vocab: [{ en: "family", es: "familia" }] },
  k18: { words: { birthday: "cumpleaños", august: "agosto" }, vocab: [{ en: "birthday", es: "cumpleaños" }, { en: "August", es: "agosto" }] },
  k19: { words: { climbing: "trepando", tree: "árbol" }, vocab: [{ en: "climbing", es: "trepando" }, { en: "tree", es: "árbol" }] },
  k20: { words: { hurt: "lastimé", back: "espalda", surfing: "surfeando", ocean: "océano" }, vocab: [{ en: "hurt", es: "lastimar" }, { en: "back", es: "espalda" }, { en: "ocean", es: "océano" }] },
  k21: { words: { post: "correos", office: "oficina", mail: "enviamos", letters: "cartas", packages: "paquetes" }, vocab: [{ en: "post office", es: "oficina de correos" }, { en: "letters", es: "cartas" }, { en: "packages", es: "paquetes" }] },
  k22: { words: { family: "familia", eat: "comemos", dining: "comedor", room: "cuarto" }, vocab: [{ en: "dining room", es: "comedor" }] },
  k23: { words: { orangutans: "orangutanes", live: "viven", zoo: "zoológico" }, vocab: [{ en: "zoo", es: "zoológico" }] },
  k24: { words: { yesterday: "ayer", rainy: "lluvioso", today: "hoy", sunny: "soleado" }, vocab: [{ en: "rainy", es: "lluvioso" }, { en: "sunny", es: "soleado" }] },
  k25: { words: { taught: "enseñé", mom: "mamá", play: "jugar", chess: "ajedrez" }, vocab: [{ en: "taught", es: "enseñé" }, { en: "chess", es: "ajedrez" }] },
  k26: { words: { clean: "limpio", room: "cuarto" }, vocab: [{ en: "clean", es: "limpiar" }, { en: "room", es: "cuarto" }] },
  k27: { words: { exercise: "ejercicio", wear: "uso", sporty: "deportiva", clothes: "ropa" }, vocab: [{ en: "exercise", es: "ejercicio" }, { en: "sporty", es: "deportivo" }] },
  k28: { words: { take: "toma", subway: "metro", city: "ciudad", bus: "autobús" }, vocab: [{ en: "subway", es: "metro" }, { en: "bus", es: "autobús" }] },
  k29: { words: { learn: "aprende", music: "música", science: "ciencia" }, vocab: [{ en: "music", es: "música" }, { en: "science", es: "ciencia" }] },
  k30: { words: { recipe: "receta", tells: "dice", make: "preparar", dish: "plato" }, vocab: [{ en: "recipe", es: "receta" }, { en: "dish", es: "plato" }] },
  k31: { words: { friends: "amigos", life: "vida", happy: "feliz", interesting: "interesante" }, vocab: [{ en: "friends", es: "amigos" }, { en: "happy", es: "feliz" }] },
  k32: { words: { young: "jóvenes", old: "mayores", everyone: "todos", fly: "volar", kite: "papalote" }, vocab: [{ en: "fly", es: "volar" }, { en: "kite", es: "papalote" }] },
  k33: { words: { like: "gusta", swim: "nadar", dance: "bailar" }, vocab: [{ en: "swim", es: "nadar" }, { en: "dance", es: "bailar" }] },
  k34: { words: { love: "encanta", playing: "tocar", piano: "piano" }, vocab: [{ en: "piano", es: "piano" }] },
  k35: { words: { past: "pasado", computers: "computadoras", really: "muy", big: "grandes" }, vocab: [{ en: "computers", es: "computadoras" }, { en: "past", es: "pasado" }] },
  k36: { words: { nine: "nueve", planets: "planetas", pluto: "Plutón", longer: "ya no", planet: "planeta" }, vocab: [{ en: "planets", es: "planetas" }, { en: "Pluto", es: "Plutón" }] },
  k37: { words: { want: "quiero", travel: "viajar", many: "muchos", countries: "países" }, vocab: [{ en: "travel", es: "viajar" }, { en: "countries", es: "países" }] },
  k38: { words: { last: "pasado", year: "año", planted: "planté", trees: "árboles" }, vocab: [{ en: "planted", es: "planté" }, { en: "trees", es: "árboles" }] },
  k39: { words: { ready: "listo", real: "de verdad", dinosaurs: "dinosaurios" }, vocab: [{ en: "ready", es: "listo" }, { en: "dinosaurs", es: "dinosaurios" }] },
  k40: { words: { important: "importante", know: "conocer", skills: "habilidades", interests: "intereses" }, vocab: [{ en: "skills", es: "habilidades" }, { en: "interests", es: "intereses" }] }
};
